#!/bin/bash

domain=$1
subdomain=$2

# Function to get DNS record information
get_dns_info() {
    local dig_output=$(dig +short $subdomain.$domain 2>/dev/null)
    if [ -n "$dig_output" ]; then
        echo "The subdomain $subdomain is a A record and points to $dig_output"
    else
        echo "No DNS record found for subdomain: $subdomain"
    fi
}

# Check if subdomain is provided, otherwise check default subdomains
if [ -z "$subdomain" ]; then
    get_dns_info www
    get_dns_info lb-01
    get_dns_info web-01
    get_dns_info web-02
else
    get_dns_info $subdomain
fi