#!/env/bin/bash

# Name of the private key
private_key="school"

# Number of bits in the key
key_bits=4096

# Passphrase to protect the key
passphrase="betty"

# Generate the key pair
ssh-keygen -t rsa -b $key_bits -N "$passphrase" -f "$private_key"

# Display the key information
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $private_key."
echo "Your public key has been saved in $private_key.pub."
echo "The key fingerprint is:"
ssh-keygen -l -E md5 -f "$private_key"
echo "The key's randomart image is:"
ssh-keygen -lv -E md5 -f "$private_key"

# Output the directory listing
ls -l "$private_key" "$private_key.pub"
